package org.apache.hadoop.fs.adl;

import java.io.File;

/**
 * Map access tokens in ~/.azure/accessTokens.json generated by Azure CLI.
 */
public class AzureADAccessToken {
  private String _authority;
  private String _clientId;
  private String accessToken;
  private int expiresIn;
  private String expiresOn;
  private boolean isMRRT;
  private String oid;
  private String refreshToken;
  private String resource;
  private String servicePrincipalId;
  private String servicePrincipalTenant;
  private String tokenType;
  private String userId;

  public static File getAccessTokensFile() {
    return new File(String.format("%s/.azure/accessTokens.json",
        System.getProperty("user.home")));
  }
  public AzureADAccessToken() {
  }

  public String get_authority() {
    return _authority;
  }

  public void set_authority(String _authority) {
    this._authority = _authority;
  }

  public String get_clientId() {
    return _clientId;
  }

  public void set_clientId(String _clientId) {
    this._clientId = _clientId;
  }

  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public int getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(int expiresIn) {
    this.expiresIn = expiresIn;
  }

  public String getExpiresOn() {
    return expiresOn;
  }

  public void setExpiresOn(String expiresOn) {
    this.expiresOn = expiresOn;
  }

  public boolean get_isMRRT() {
    return isMRRT;
  }

  public void setisMRRT(boolean isMRRT) {
    this.isMRRT = isMRRT;
  }

  public String getOid() {
    return oid;
  }

  public void setOid(String oid) {
    this.oid = oid;
  }

  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }

  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public String getServicePrincipalId() {
    return servicePrincipalId;
  }

  public void setServicePrincipalId(String servicePrincipalId) {
    this.servicePrincipalId = servicePrincipalId;
  }

  public String getServicePrincipalTenant() {
    return servicePrincipalTenant;
  }

  public void setServicePrincipalTenant(String servicePrincipalTenant) {
    this.servicePrincipalTenant = servicePrincipalTenant;
  }

  public String getTokenType() {
    return tokenType;
  }

  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }
}
